#!/usr/bin/env python3
"""Backlog agent: fetches a GitHub issue and implements it using Claude Code.

Usage:
    python agent/backlog_agent.py <issue-number>

Example:
    python agent/backlog_agent.py 10

The agent will:
  1. Fetch the issue title and body from GitHub
  2. Run Claude Code non-interactively to implement it
  3. Commit the changes to a new branch and open a PR

Requirements:
  - ANTHROPIC_API_KEY set in environment
  - GH_TOKEN or `gh auth login` for GitHub access
  - `claude` CLI installed: npm install -g @anthropic-ai/claude-code
"""

import json
import subprocess
import sys
from pathlib import Path

# jobApplications/ — the only directory the agent is allowed to write to.
REPO_ROOT = Path(__file__).resolve().parent.parent


def build_allowed_tools(repo_root: Path) -> list[str]:
    """Tool grants for the non-interactive `claude` run, scoped to repo_root.

    Edit/Write are confined to repo_root via path glob. Bash can't be path-scoped
    (its rules match command text, not files touched), so it's limited to a
    whitelist of the commands the agent actually needs instead of blanket "Bash".
    """
    return [
        "Read",
        "Glob",
        "Grep",
        f"Edit({repo_root}/**)",
        f"Write({repo_root}/**)",
        "Bash(git *)",
        "Bash(python -m pytest*)",
        "Bash(python3 -m pytest*)",
        "Bash(pytest*)",
    ]


def get_issue(issue_number: int) -> dict:
    result = subprocess.run(
        ["gh", "issue", "view", str(issue_number),
         "--json", "number,title,body,labels"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def run_agent(issue: dict) -> bool:
    prompt = f"""You are a software engineer implementing a feature from the GitHub issue backlog.

Issue #{issue['number']}: {issue['title']}

---
{issue['body']}
---

Follow these steps:
1. Read CLAUDE.md first — it defines all project conventions you must follow.
2. Understand the existing code structure before making any changes.
3. Write unit tests first (in tests/), then implement to make them pass.
4. Run `python -m pytest tests/ -q` and fix any failures before finishing.
5. Do NOT commit, push, or open a PR — the workflow handles that.

Be thorough. Follow the design guidelines in CLAUDE.md exactly."""

    print(f"\n→ Running Claude agent on issue #{issue['number']}: {issue['title']}\n")

    proc = subprocess.run(
        [
            "claude",
            "-p", prompt,
            "--allowedTools", ",".join(build_allowed_tools(REPO_ROOT)),
            "--permission-mode", "acceptEdits",
            "--output-format", "json",
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
    )

    try:
        output = json.loads(proc.stdout)
        print(output.get("result", "").strip())
        cost = output.get("total_cost_usd")
        if cost:
            print(f"\nAgent cost: ${cost:.4f}")
    except (json.JSONDecodeError, AttributeError):
        print(proc.stdout)

    if proc.returncode != 0:
        print(f"\nAgent exited with error:\n{proc.stderr}", file=sys.stderr)
        return False

    return True


def create_pr(issue: dict) -> None:
    branch = f"agent/issue-{issue['number']}"

    subprocess.run(["git", "checkout", "-b", branch], cwd=REPO_ROOT, check=True)

    # Stage only modified tracked files + new files in code directories.
    # Never use -A — the repo has untracked mobile/, docs/, logs/ etc.
    # that must not be swept into agent PRs.
    subprocess.run(["git", "add", "-u"], cwd=REPO_ROOT, check=True)
    for code_dir in ["pipeline", "tests", "web", "config", "agent"]:
        if (REPO_ROOT / code_dir).is_dir():
            subprocess.run(["git", "add", code_dir], cwd=REPO_ROOT, check=True)

    # Check if there's anything staged
    diff_check = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=REPO_ROOT)
    if diff_check.returncode == 0:
        print("Agent made no file changes — nothing to commit.")
        return

    subprocess.run([
        "git", "commit", "-m",
        f"Implement #{issue['number']}: {issue['title']}\n\n"
        f"Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>",
    ], cwd=REPO_ROOT, check=True)

    subprocess.run(["git", "push", "-u", "origin", branch], cwd=REPO_ROOT, check=True)

    subprocess.run([
        "gh", "pr", "create",
        "--title", f"[Agent] {issue['title']}",
        "--body", (
            f"Implements #{issue['number']}\n\n"
            f"Generated by the backlog agent. Please review before merging.\n\n"
            f"**Checklist:**\n"
            f"- [ ] Tests pass\n"
            f"- [ ] Code follows project conventions\n"
            f"- [ ] No unintended changes"
        ),
        "--base", "main",
    ], cwd=REPO_ROOT, check=True)

    print(f"\n✓ PR opened for issue #{issue['number']}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python agent/backlog_agent.py <issue-number>")
        sys.exit(1)

    issue_number = int(sys.argv[1])
    issue = get_issue(issue_number)
    success = run_agent(issue)

    if not success:
        sys.exit(1)

    create_pr(issue)
